/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface RunRequest
 */
export interface RunRequest {
    /**
     * 
     * @type {string}
     * @memberof RunRequest
     */
    command: string;
}

/**
 * Check if a given object implements the RunRequest interface.
 */
export function instanceOfRunRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "command" in value;

    return isInstance;
}

export function RunRequestFromJSON(json: any): RunRequest {
    return RunRequestFromJSONTyped(json, false);
}

export function RunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'command': json['command'],
    };
}

export function RunRequestToJSON(value?: RunRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'command': value.command,
    };
}

